import os


DATABASE_URI = os.environ.get('DATABASE_URI')
JWT_KEY = os.environ.get('JWT_KEY')
class Config:
    SQLALCHEMY_DATABASE_URI = DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    JWT_SECRET_KEY = JWT_KEY