import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}
      >
        <main className="">
          <div className="relative min-h-screen">
            <Image
              className="fixed bottom-0 left-0 -z-10 h-3/4 w-full"
              width={100}
              height={100}
              src="/bgvec.svg"
              alt="bg-vector"
            />
            <Image
              className="fixed inset-0 -z-20 h-screen w-full object-cover"
              fill={false}
              width={1920}
              height={1080}
              src="/circle.png"
              alt="circle-bg"
              priority
            />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
